---
# tasks file for bond
- name: Ethernet Bond
  arista.eos.eos_lag_interfaces:
    config:
      - name: 100
        members:
          - member: Ethernet1
            mode: active
          - member: Ethernet2
            mode: active
    state: merged

- name: Set Ethernet
  arista.eos.eos_interfaces:
    config:
      - name: Port-Channel100
        description: uplink-juniper
        mtu: 1514
    state: merged

- name: Set L2
  arista.eos.eos_l2_interfaces:
    config:
      - name: Port-Channel100
        mode: trunk
        trunk:
          native_vlan: 1
          # trunk_allowed_vlans:
          #   - 10
        # access:
        #   vlan: 10
    state: merged
