---
# tasks file for snmp
- name: Juniper SRX
  when:
    - ansible_network_os == 'junipernetworks.junos.junos'
  ansible.builtin.include_tasks: juniper_junos/snmp.yml

- name: Arista EOS
  when:
    - ansible_network_os == 'arista.eos.eos'
  ansible.builtin.include_tasks: arista_eos/snmp.yml

- name: Cisco IOS
  when:
    - ansible_network_os == 'cisco.ios.ios'
  ansible.builtin.include_tasks: cisco_ios/snmp.yml
