---
# tasks file for initial_cfg
- name: Arista EOS - Initial Cfg - Set Basic System
  arista.eos.eos_system:
    hostname: "{{ hostname }}"
    domain_name: "{{ domain_name }}"
    domain_search:
      - hkn.lab
    name_servers: "{{ inventory_dns_servers }}"
    state: present

- name: Arista EOS - Initial Cfg - Set Admin User
  arista.eos.eos_user:
    aggregate:
      - name: admin
        privilege: 15
        # sshkey: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
        configured_password: "{{ admin_password }}"
        update_password: always
        state: present
