---
# tasks file for vlan
- name: Juniper SRX - AAA - RADIUS - Set
  failed_when: false
  when:
    - ansible_network_os == 'junipernetworks.junos.junos'
  junipernetworks.junos.junos_config:
    src: juniper_junos/radius.j2
