---
# tasks file for vlan
- name: Juniper JunOS - AAA - TACACS+ - Set
  failed_when: false
  when:
    - ansible_network_os == 'junipernetworks.junos.junos'
  junipernetworks.junos.junos_config:
    src: juniper_junos/tacacs.j2
