---
# tasks file for vlan
- name: Set VLANs
  junipernetworks.junos.junos_vlans:
    state: replaced
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.vlan_id }}"
        # l3_interface: irb.{{ item.vlan_id }}
  loop: "{{ inventory_vlans | combine(device_vlans) }}"
