---
# tasks file for vlan
- name: Juniper SRX - VLAN - Set
  with_items: 
    - "{{ [inventory_vlans, device_vlans] | community.general.lists_mergeby('name') }}"
  junipernetworks.junos.junos_vlans:
    state: replaced
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.vlan_id }}"
        # l3_interface: irb.{{ item.vlan_id }}
