---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-v'
  ANSIBLE_GALAXY_CLI_ROLE_OPTS: '-v'

dependencies:
  python:
    - netaddr
    - ansible-pylibssh
    - python-nmap
  system:
    - nmap [platform:rpm]
  galaxy: collections/requirements.yml
  ansible_core:
    package_pip: ansible-core==2.14.14
  ansible_runner:
    package_pip: ansible-runner>==2.3.4
  # python_interpreter:
  #   package_system: "python311"
  #   python_path: "/usr/bin/python3.11"

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

# additional_build_files:
#   - src: files/ansible.cfg
#     dest: configs

# additional_build_steps:
#   prepend_galaxy:
#     - ADD _build/configs/ansible.cfg ~/.ansible.cfg
#   prepend_final: |
#     RUN whoami
#     RUN cat /etc/os-release
#   append_final:
#     - RUN echo This is a post-install command!
#     - RUN ls -la /etc

options:
    # container_init:
    #     package_pip: dumb-init>=1.2.5
    #     entrypoint: '["dumb-init"]'
    #     cmd: '["csh"]'
    package_manager_path: /usr/bin/microdnf
    skip_ansible_check: False
    user: '1000'
    workdir: /runner
