---
roles: []
  # - name:
  #   version:
collections:
  - name: arista.eos
  - name: cisco.ios
  # - name: cisco.nxos
  - name: community.network
  - name: community.general
  - name: junipernetworks.junos
