---
# tasks file for initial_cfg
# - name: Set L3
#   ignore_errors: true
#   arista.eos.eos_l3_interfaces:
#     config:
#       - name: Vlan1 # Network
#         ipv4:
#           - address: 172.16.0.3/22
#       - name: Vlan10 # Personal
#         ipv4:
#           - address: 172.16.10.3/23
#       - name: Vlan666 # IoT
#         ipv4:
#           - address: 172.16.66.3/23
#       - name: Vlan99 # IPMI
#         ipv4:
#           - address: 172.16.99.3/24
#       - name: Vlan100 # NAS
#         ipv4:
#           - address: 172.16.100.3/22
#       - name: Vlan110 # Metal
#         ipv4:
#           - address: 172.16.110.3/23
#       - name: Vlan120 # Virtual
#         ipv4:
#           - address: 172.16.120.3/22
#       - name: Vlan140 # OCP4
#         ipv4:
#           - address: 172.16.140.3/22
#       - name: Vlan247 # Media
#         ipv4:
#           - address: 172.16.247.3/24
#       - name: Vlan24 # WIFI
#         ipv4:
#           - address: 172.16.251.3/24
#       - name: Vlan67 # DHCP/VPN
#         ipv4:
#           - address: 172.16.254.3/23
#     state: merged
