---
# tasks file for vlan
- name: Arista EOS - VLAN L3 - Set
  failed_when: false
  loop:
    - "{{ inventory_vlans | combine(device_vlans) }}"
  arista.eos.eos_l3_interfaces:
    state: replaced
    config:
      - name: "Vlan {{ item.vlan_id }}"
        ipv4:
          - address: "{{ item.subnets[0] }}"
          # - address: "{{ item.subnets[1] | default(omit) }}"
          #   secondary: true
