---
# tasks file for vlan
- name: Arista EOS - VLAN
  when:
    - ansible_network_os == 'arista.eos.eos'
  ansible.builtin.include_tasks: arista_eos/vlan.yml

- name: Arista EOS - VLAN L3
  when:
    - ansible_network_os == 'arista.eos.eos'
    - not network_role_l3_disable
  ansible.builtin.include_tasks: arista_eos/l3.yml
