---
# tasks file for vlan
- name: Set VLANs
  arista.eos.eos_vlans:
    state: replaced
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.vlan_id }}"
        state: active
  with_items: "{{ inventory_vlans | combine(device_vlans) }}"
