---
# tasks file for vlan
- name: Set L3
  failed_when: false
  community.network.icx_l3_interfaces:
    state: replaced
    config:
      - name: "Vlan {{ item.vlan_id }}"
        ipv4:
          - address: "{{ item.subnets[0] }}"
          # - address: "{{ item.subnets[1] | default(omit) }}"
          #   secondary: true
  with_items: "{{ inventory_vlans | combine(device_vlans) }}"
