---
# tasks file for vlan
- name: Brocade ICX VLANs
  ansible.builtin.include_tasks: brocade_icx/vlan.yml
  when:
    - ansible_network_os == 'community.network.icx'

- name: Brocade ICX VLAN L3
  ansible.builtin.include_tasks: brocade_icx/l3.yml
  when:
    - ansible_network_os == 'community.network.icx'
    - not network_role_disable_l3
