---
# tasks file for vlan
- name: Set VLANs
  community.network.icx_vlan:
    state: present
    aggregate:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.vlan_id }}"
        state: present
  loop: "{{ [inventory_vlans, device_vlans] | community.general.lists_mergeby('name') }}"
