---
# tasks file for vlan
- name: Brocade ICX - VLAN - Set
  with_items: 
    - "{{ [inventory_vlans, device_vlans] | community.general.lists_mergeby('name') }}"
  community.network.icx_vlan:
    state: present
    aggregate:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.vlan_id }}"
        state: present
