---
# tasks file for aaa
- name: Arista EOS - AAA
  when:
    - ansible_network_os == 'arista.eos.eos'
  ansible.builtin.include_tasks: arista_eos/main.yml

- name: Cisco IOS - AAA
  when:
    - ansible_network_os == 'cisco.ios.ios'
  ansible.builtin.include_tasks: cisco_ios/main.yml

- name: Juniper SRX - AAA
  when:
    - ansible_network_os == 'junipernetworks.junos.junos'
  ansible.builtin.include_tasks: juniper_junos/main.yml
