---
# tasks file for port_forward
- name: Juniper SRX - Port Forward - Unset - Security Policy # for {{ item.name }}
  ignore_errors: true
  with_items: 
    - "{{ inventory_port_forward_disabled }}"
  vars:
    ansible_command_timeout: 180
  junipernetworks.junos.junos_config:
    update: update
    lines:
      - edit security policies from-zone {{ item.source_zone }} to-zone {{ item.target_zone }}
      - delete policy Port-Forward-{{ item.target_host }} match application {{ item.name }}
      - exit

- name: Juniper SRX - Port Forward - Unset - DNAT # for {{ item.name }}
  ignore_errors: true
  with_items: 
    - "{{ inventory_port_forward_disabled }}"
  vars:
    ansible_command_timeout: 180
  junipernetworks.junos.junos_config:
    update: update
    lines:
      - edit security nat destination 
      - delete pool {{ item.name }}
      - delete rule-set {{ item.rule_set }} rule {{ item.name }}

- name: Juniper SRX - Port Forward - Unset - Application # for {{ item.name }}
  ignore_errors: true
  with_items: 
    - "{{ inventory_port_forward_disabled }}"
  vars:
    ansible_command_timeout: 180
  junipernetworks.junos.junos_config:
    update: update
    lines:
      - delete applications application {{ item.name }}


