---
# tasks file for aaa
- name: Arista EOS - AAA - RADIUS
  when:
    - ansible_network_os == 'arista.eos.eos'
    - network_role_use_radius
  ansible.builtin.include_tasks: arista_eos/radius.yml

- name: Arista EOS - AAA - TACACS+
  when:
    - ansible_network_os == 'arista.eos.eos'
    - network_role_use_tacacs
  ansible.builtin.include_tasks: arista_eos/tacacs.yml
