---
# handlers file for initial_cfg
- name: Arista EOS - Commit
  arista.eos.eos_command:
    commands:
      - write

- name: Juniper SRX - Commit
  juniper.device.command:
    commands:
      - commit and-quit
