---
# tasks file for initial_cfg
- name: Set Basic System Cfg
  arista.eos.eos_system:
    hostname: "{{ hostname }}"
    domain_name: "{{ domain_name }}"
    domain_search: 
      - hkn.lab
    name_servers:
      - "172.16.1.13"
      - "172.16.1.11"
    state: present

- name: Set Admin User
  arista.eos.eos_user:
    aggregate:
      - name: admin
        privilege: 15
        # sshkey: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
        configured_password: "{{ admin_password }}"
        update_password: always
        state: present
