---
# tasks file for initial_cfg
- name: Set Basic System Cfg
  junipernetworks.junos.junos_system:
    hostname: "{{ hostname }}"
    domain_name: "{{ domain_name }}"
    domain_search: 
      - hkn.lab
    name_servers:
      - "172.16.1.13"
      - "172.16.1.11"
    state: present

- name: Set Admin Cfg
  junipernetworks.junos.junos_user:
    aggregate:
      - name: admin
        role: "super-user"
        # sshkey: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
        encrypted_password: "{{ admin_password | password_hash('sha512') }}"
        state: present
