---
# tasks file for ethernet
- name: Set L2
  arista.eos.eos_l2_interfaces:
    state: replaced
    config:
      - name: "{{ item.iface_name }}"
        mode: "{{ item.port_mode | default('trunk') }}"
        access:
          vlan: "{{ item.native_vlan_id | default(omit) }}"
        trunk:
          native_vlan: "{{ item.native_vlan_id | default(omit) }}"
          trunk_allowed_vlans: "{{ item.allowed_vlan_ids | default(omit) }}"
  loop: "{{ device_lan_ports }}"
