---
# tasks file for ethernet
- name: Arista EOS - Ethernet - Set L3
  arista.eos.eos_l3_interfaces:
    state: replaced
    config:
      # - name: Vlan 1
      #   ipv4:
      #     - address: 172.16.0.3/16
