---
# tasks file for aaa
- name: Cisco IOS - AAA - RADIUS
  when:
    - ansible_network_os == 'cisco.ios.ios'
    - not network_role_use_radius
  ansible.builtin.include_tasks: cisco_ios/radius.yml

- name: Cisco IOS - AAA - TACACS+
  when:
    - ansible_network_os == 'cisco.ios.ios'
    - not network_role_use_tacacs
  ansible.builtin.include_tasks: cisco_ios/tacacs.yml
