---
dependency:
  name: galaxy
  enabled: False
  options:
    ignore-errors: True
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint
  ansible-lint
