---
# tasks file for vlan
- name: Cisco IOS - VLAN - Transparency Mode
  when:
    - ansible_network_os == 'cisco.ios.ios'
  cisco.ios.ios_config:
    lines:
      - vtp mode transparent

- name: Cisco IOS - VLAN
  when:
    - ansible_network_os == 'cisco.ios.ios'
  ansible.builtin.include_tasks: cisco_ios/vlan.yml

- name: Cisco IOS - VLAN L3
  when:
    - ansible_network_os == 'cisco.ios.ios'
    - not network_role_l3_disable
  ansible.builtin.include_tasks: cisco_ios/l3.yml
