---
# tasks file for users
- name: Arista EOS - User
  when:
    - ansible_network_os == 'arista.eos.eos'
  ansible.builtin.include_tasks: arista_eos/main.yml

- name: Cisco IOS - User
  when:
    - ansible_network_os == 'cisco.ios.ios'
  ansible.builtin.include_tasks: cisco_ios/main.yml
