---
# tasks file for ethernet
- name: Cisco IOS - Ethernet - Set Ethernet
  arista.eos.eos_interfaces:
    state: replaced
    config:
      - name: "{{ item.iface_name }}"
        description: "{{ item.port_name }}"
        mode: layer2
  with_items: "{{ device_lan_ports }}"
