---
# tasks file for tftp
- name: Set tftp server option
  loop: "{{ inventory_tftp_config | subelements('tftp_config') }}"
  when:
    - (item.1.option is defined)
  failed_when: false
  arista.eos.eos_config:
    parents:
      - dhcp server
      - subnet {{ item.0.network }}
    lines:
      - tftp server option {{ item.1.option }} {{ item.1.server }}

- name: Set tftp file option
  loop: "{{ inventory_tftp_config | subelements('tftp_config') }}"
  when:
    - (item.1.file is defined)
  failed_when: false
  arista.eos.eos_config:
    parents:
      - dhcp server
      - subnet {{ item.0.network }}
    lines:
      - tftp server file {{ item.1.file }}
