---
# tasks file for users
- name: Add User
  cisco.ios.ios_user:
    name: "{{ item.user }}"
    privilege: "{{ item.privilege }}"
    configured_password: "{{ item.password }}"
    password_type: "password"
    sshkey: "{{ default(omit) }}"
  with_items: "{{ inventory_users }}"
  no_log: true
