---
- name: Configure SNMP Server
  junipernetworks.junos.junos_snmp_server:
    state: rendered
    config:
      contact: "{{ inventory_snmp.contact }}"
      location: "{{ inventory_snmp.location }}"
      communities:
        - name: "{{ inventory_snmp.v2.community }}"
          authorization: "read-write"
          # clients: "{{ inventory_snmp.v2.clients | default(omit) }}"
          view: all
        - name: public
          authorization: "read-only"
          # clients: "{{ inventory_snmp.v2.clients | default(omit) }}"
      views:
        - name: all
          oids:
            - oid: ".1"
