---
# tasks file for base
- name: Set System
  cisco.ios.ios_system:
    hostname: "{{ inventory_hostname }}"
    domain_name: network.hkn.lab
    name_servers: "{{ inventory_dns_servers }}"

- name: Set Default Gateway
  cisco.ios.ios_config:
    lines:
      - ip default-gateway {{ inventory_gateway }}

# - name: Set enable password
#   cisco.ios.ios_config:
