---
# tasks file for base
- name: Arista EOS - Base Configuration
  when: 
    - ansible_network_os == 'arista.eos.eos'
  ansible.builtin.include_tasks: arista_eos/main.yml

- name: Brocade ICX - Base Configuration
  when: 
    - ansible_network_os == 'community.network.icx'
  ansible.builtin.include_tasks: brocade_icx/main.yml

- name: Cisco IOS - Base Configuration
  when: 
    - ansible_network_os == 'cisco.ios.ios'
  ansible.builtin.include_tasks: cisco_ios/main.yml

- name: Juniper Junos - Base Configuration
  when: 
    - ansible_network_os == 'junipernetworks.junos.junos'
  ansible.builtin.include_tasks: juniper_junos/main.yml
