---
# tasks file for ethernet
- name: Set Ethernet
  arista.eos.eos_interfaces:
    config:
      - name: Port-Channel100
        description: uplink-juniper
        mtu: 1514

      - name: Ethernet1
        description: uplink-juniper-1
      - name: Ethernet2
        description: uplink-juniper-2
      - name: Ethernet3
        description: nas-spartan

      - name: Ethernet6/1
        description: uplink-arista-brocade-1
      - name: Ethernet6/2
        description: uplink-arista-brocade-2
      - name: Ethernet6/3
        description: uplink-arista-brocade-3
      - name: Ethernet6/4
        description: uplink-arista-brocade-4

      # - name: Ethernet29
      #   description:
      - name: Ethernet30
        description: host1
      # - name: Ethernet31
      #   description:
      - name: Ethernet32
        description: host2
      # - name: Ethernet33
      #   description:
      - name: Ethernet34
        description: host3
      - name: Ethernet35
        description: personal-desktop

      - name: Ethernet36
        description:  r720
        mode: layer2
        # speed: 40Gig
        # mtu: 9216
        enabled: true
    state: merged

- name: Set L2
  arista.eos.eos_l2_interfaces:
    config:
      - name: Ethernet6/1
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet6/2
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet6/3
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet6/4
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:

      - name: Ethernet7/1
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet7/1
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet7/1
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet7/1
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:

      - name: Ethernet29
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet30
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet31
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet32
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet33
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet34
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet35
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
      - name: Ethernet36
        mode: trunk
        # access:
        #   vlan:
        # trunk:
        #   native_vlan:
        #   trunk_allowed_vlans:
    state: merged

# - name: Set L3
#   arista.eos.eos_l3_interfaces:
#     config:
#       - name: Vlan1
#         ipv4:
#           - address: 172.16.0.3/16
#       - name: Vlan10
#         ipv4:
#           - address: 172.16.10.3/24
#       - name: Vlan11
#         ipv4:
#           - address: 172.16.249.3/24
#       # - name: Vlan67
#       #   ipv4:
#       #     - address: 172.16.254.3/24
#       - name: Vlan99
#         ipv4:
#           - address: 172.16.99.3/24
#       - name: Vlan100
#         ipv4:
#           - address: 172.16.100.3/24
#       - name: Vlan110
#         ipv4:
#           - address: 172.16.110.3/24
#       - name: Vlan130
#         ipv4:
#           - address: 172.16.130.3/24
#       - name: Vlan140
#         ipv4:
#           - address: 172.16.140.3/24
#       - name: Vlan247
#         ipv4:
#           - address: 172.16.247.3/24
#       - name: Vlan666
#         ipv4:
#           - address: 172.16.66.3/24
#     state: merged
