# task file for routes
---
- name: Set Route
  arista.eos.eos_static_routes:
    config:
      - vrf: default
        address_families:
          - afi: ipv4
            routes:
              - dest: "{{ item.destination }}"
                next_hops:
                  - vrf: default
                    interface: "{{ item.route }}"
                    # description: default internet route
    state: replaced
  with_items: "{{ inventory_static_routes }}"
