name: ansible-lint
run-name: Ansible Linting
on:
  push:
    branches: [main]
  pull_request: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: ""
          setup_python: "true"
          python_version: "3.13"
          working_directory: ""
          requirements_file: ""
