---
name: Deploy Collection

# Trigger the workflow however you prefer
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: GALAXY_PUBLIC
    steps:
      - uses: actions/checkout@v3

      - name: Get the version name from the tags
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Update galaxy.yml
        run: "sed -i -e 's/^version: .*/version: ${{ env.RELEASE_VERSION }}/g' galaxy.yml"

      - name: Build Collection
        uses: hyperkineticnerd/github-action-galaxy-build@HEAD
        with:
          options: --force

      - name: Deploy Collection
        uses: hyperkineticnerd/github-action-galaxy-publish@HEAD
        with:
          options: '--api-key ${{ secrets.GALAXY_API_KEY }}'
          archive: '${{ env.GITHUB_WORKSPACE }}/hyperkineticnerd-network-${{ env.RELEASE_VERSION }}.tar.gz'
