---
- name: Create dhcp server
  arista.eos.eos_config:
    before: no dhcp server
    lines:
      - dhcp server

- name: Create dhcp subnet
  loop: "{{ inventory_dhcp_pools }}"
  arista.eos.eos_config:
    parents:
      - dhcp server
    lines:
      - subnet {{ item.network }}

- name: Set subnet options
  loop: "{{ inventory_dhcp_pools }}"
  arista.eos.eos_config:
    parents:
      - dhcp server
      - subnet {{ item.network }}
    lines:
      - default-gateway {{ item.router[0] }}
      - dns server {{ item.dns | join(' ') }}
      - range {{ item.range.low }} {{ item.range.high }}

- name: Create reservations pool
  loop: "{{ inventory_dhcp_pools }}"
  arista.eos.eos_config:
    parents:
      - dhcp server
      - subnet {{ item.network }}
    lines:
      - reservations

- name: Set reservations
  when:
    # - item.reservations is defined
    - item.0.network | ansible.utils.network_in_usable( item.1.addr )
  loop: "{{ inventory_dhcp_pools | subelements('reservations') }}"
  failed_when: false
  arista.eos.eos_config:
    parents:
      - dhcp server
      - subnet {{ item.0.network }}
      - reservations
    lines:
      - mac-address {{ item.1.mac | ansible.utils.hwaddr('cisco') }}
      - ipv4-address {{ item.1.addr }}
