# - name: Set Reservations
#   ansible.builtin.debug:
#     var=inner_item
#   loop: "{{ outer_item.reservations }}"
#   loop_control:
#     loop_var: inner_item
#   ignore_errors: true

- name: Set MAC
  arista.eos.eos_config:
    backup: true
    # replace: block
    parents: 
      - dhcp server
      -   subnet {{ outer_item.network }}
      -     reservations
    lines:
      - mac-address {{ inner_item.mac }}
  loop: "{{ outer_item.reservations }}"
  loop_control:
    loop_var: inner_item
  ignore_errors: true

- name: Set IP
  arista.eos.eos_config:
    backup: true
    # replace: block
    parents: 
      - dhcp server
      -   subnet {{ outer_item.network }}
      -     reservations
      -       mac-address {{ inner_item.mac }}
    lines:
      - ipv4-address {{ inner_item.addr }}
  loop: "{{ outer_item.reservations }}"
  loop_control:
    loop_var: inner_item
  ignore_errors: true
