---
- name: Create dhcp server
  arista.eos.eos_config:
    before: no dhcp server
    lines:
      - dhcp server

- name: Create dhcp subnet
  loop: "{{ inventory_dhcp_pools[0] }}"
  arista.eos.eos_config:
    parents:
      - dhcp server
    lines:
      - subnet {{ inventory_dhcp_pools[0].network }}

- name: Set reservations
  when: "item.reservations is defined"
  loop: "{{ inventory_dhcp_pools | subelements('reservations') }}"
  arista.eos.eos_config:
    parents:
      - dhcp server
      - subnet {{ inventory_dhcp_pools.0.network }}
      - reservations
    lines:
      - mac-address {{ item.1.mac| ansible.utils.hwaddr('cisco') }}
      - ipv4-address {{ item.1.addr }}

- name: Set subnet options
  loop: "{{ inventory_dhcp_pools[0] }}"
  arista.eos.eos_config:
    parents:
      - dhcp server
      - subnet {{ inventory_dhcp_pools[0].network }}
    lines:
      - default-gateway {{ inventory_dhcp_pools[0].router[0] }}
      - dns server {{ inventory_dhcp_pools[0].dns | join(' ') }}
      - range {{ inventory_dhcp_pools[0].range.low }} {{ inventory_dhcp_pools[0].range.high }}
